In [5]:
import numpy as np

对于ndarray结构来说，里面所有的元素必须是同一类型的
如果不是的话，会自动的向下进行转换

In [6]:
tang_list = [1,2,3,4,5]
tang_array = np.array(tang_list)
tang_array

array([1, 2, 3, 4, 5])

ndarray基本属性操作

In [7]:
type(tang_array)

numpy.ndarray

In [8]:
tang_array.dtype

dtype('int32')

In [9]:
tang_array.itemsize

4

In [10]:
tang_array.shape

(5,)

In [11]:
tang_array.size

5

In [8]:
np.size(tang_array)

5

In [9]:
np.shape(tang_array)

(5,)

In [11]:
tang_array.ndim

1

In [12]:
np.ndim(tang_array)

1

In [13]:
tang_array

array([1, 2, 3, 4, 5])

In [14]:
tang_array.fill(0)
tang_array

array([0, 0, 0, 0, 0])

索引与切片:跟Python都是一样的 还是从0开始的

In [15]:
tang_list = [1,2,3,4,5]
tang_array = np.array(tang_list)
tang_array[0]

1

In [16]:
#:这里其实是区间的意思

In [17]:
tang_array[1:3]

array([2, 3])

In [18]:
#-2:这里就直接不给一个区间的结束，只说开头

In [19]:
tang_array[-2:]

array([4, 5])

矩阵格式（多维的形式）

In [30]:
tang_array = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
tang_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
tang_array.shape #3个维度，每个维度3个数值

(3, 3)

In [27]:
tang_array.size #数量总数

9

In [28]:
tang_array.ndim #维度数量

2

In [4]:
tang_array[1,1] #第二行中第二个数值

NameError: name 'tang_array' is not defined

In [30]:
tang_array[1,1] = 10 #替换第二行第二个数值
tang_array

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

In [31]:
tang_array[1] #第二行

array([ 4, 10,  6])

In [32]:
tang_array[:,1]   #每一个行的第二个数值

array([ 2, 10,  8])

In [37]:
tang_array[0,0:2] #第一行，第一个到第三个之间

array([1, 2])

In [34]:
tang_array

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

In [35]:
tang_array2 = tang_array
tang_array2

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

In [36]:
tang_array2[1,1] = 100 #第二行第二个替换100
tang_array2

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [37]:
tang_array

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [38]:
tang_array2 = tang_array.copy() #不加copy的话会array和array1会相同
tang_array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
tang_array2[1,1] = 10000
tang_array2

NameError: name 'tang_array2' is not defined

In [8]:
tang_array

NameError: name 'tang_array' is not defined

In [21]:
tang_array = np.arange(0,100,10)  #0-100的数值中，每个数值差10
tang_array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [1]:
mask = np.array([0,0,0,1,1,1,0,0,1,1],dtype=bool)  #先对于一个对一个范围的数值赋予布尔
mask

NameError: name 'np' is not defined

In [51]:
tang_array[mask] #再把这个布尔的数值赋予到Array之中

array([30, 40, 50, 80, 90])

In [52]:
random_array = np.random.rand(10) #顺机一个范围的数值
random_array

array([0.39478488, 0.49034841, 0.35676353, 0.55502344, 0.09861041,
       0.31610543, 0.23825337, 0.75127542, 0.24159437, 0.40845311])

In [53]:
mask = random_array > 0.5  #bool测试
mask

array([False, False, False,  True, False, False, False,  True, False,
       False])

In [54]:
tang_array[mask]

array([30, 70])

In [55]:
tang_array = np.array([10,20,30,40,50])
tang_array > 30

array([False, False, False,  True,  True])

In [56]:
np.where(tang_array > 30)  #range中那几个数值大于规定值

(array([3, 4], dtype=int64),)

In [3]:
tang_array[np.where(tang_array > 30)]  #range中大于规定值的具体数值

NameError: name 'tang_array' is not defined

In [2]:
tang_array = np.array([1,2,3,4,5],dtype=np.float32) #改变数值的type 从int到float
tang_array

NameError: name 'np' is not defined

In [9]:
tang_array.dtype

NameError: name 'tang_array' is not defined

In [10]:
tang_array.nbytes

NameError: name 'tang_array' is not defined

In [62]:
tang_array = np.array([1,10,3.5,'str'],dtype = np.object)
tang_array

C:\Users\RCY19\AppData\Local\Temp\ipykernel_18148\3813702755.py:1: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  tang_array = np.array([1,10,3.5,'str'],dtype = np.object)


array([1, 10, 3.5, 'str'], dtype=object)

In [75]:
tang_array * 2

array([ 2,  4,  6,  8, 10])

In [78]:
tang_array = np.array([1,2,3,4,5])
np.asarray(tang_array,dtype = np.float32) #asarray就可以改变之前array的结构

array([1., 2., 3., 4., 5.], dtype=float32)

In [84]:
tang_array

array([1, 2, 3, 4, 5])

In [85]:
tang_array2 = np.asarray(tang_array,dtype = np.float32)
tang_array2 

array([1., 2., 3., 4., 5.], dtype=float32)

In [87]:
tang_array #不会改变原始的array类型

array([1, 2, 3, 4, 5])

In [88]:
tang_array.astype(np.float32)

array([1., 2., 3., 4., 5.], dtype=float32)

In [89]:
tang_array 

array([1, 2, 3, 4, 5])