In [18]:
import numpy as np

In [19]:
x = np.array([5,5])
y = np.array([2,2])

In [20]:
np.multiply(x,y)

array([10, 10])

In [21]:
np.dot(x,y) #2*5加2*5

20

In [22]:
x.shape

(2,)

In [23]:
y.shape

(2,)

In [24]:
x.shape = 2,1

In [25]:
x

array([[5],
       [5]])

In [26]:
np.dot(x,y)

ValueError: shapes (2,1) and (2,) not aligned: 1 (dim 1) != 2 (dim 0)

In [27]:
y.shape = 1,2
y

array([[2, 2]])

In [28]:
x

array([[5],
       [5]])

In [29]:
print (x.shape)
print (y.shape)

(2, 1)
(1, 2)


In [30]:
np.dot(x,y)

array([[10, 10],
       [10, 10]])

In [31]:
np.dot(y,x)

array([[20]])

In [32]:
x = np.array([1,1,1])
y = np.array([[1,2,3],[4,5,6]])
print (x * y)

[[1 2 3]
 [4 5 6]]


In [33]:
y = np.array([1,1,1,4])
x = np.array([1,1,1,2])
x == y

array([ True,  True,  True, False])

In [34]:
np.logical_and(x,y) #逻辑与（可以说是并且））是真

array([ True,  True,  True,  True])

In [24]:
 np.logical_or(x,y) #非是真

array([ True,  True,  True,  True], dtype=bool)

In [25]:
np.logical_not(x,y)

array([0, 0, 0, 0])