### Numpy的随机模块

In [2]:
import numpy as np
#所有的值都是从0到1
np.random.rand(3,2)

array([[0.90996059, 0.12062906],
       [0.21672941, 0.32216281],
       [0.53494596, 0.85768536]])

In [3]:
#返回的是随机的整数，左闭右开
np.random.randint(10,size = (5,4))

array([[6, 1, 9, 1],
       [5, 8, 1, 6],
       [7, 9, 5, 6],
       [6, 0, 0, 4],
       [8, 1, 5, 9]])

In [5]:
np.random.rand()

0.47657924155392584

In [6]:
np.random.random_sample()

0.8809278052752827

In [9]:
np.random.randint(0,10,3) #0-10之间找3个数

array([3, 2, 5])

In [11]:
mu, sigma = 0,0.1 #先确定数值的均值和标准差
np.random.normal(mu,sigma,10)

array([-0.17135027, -0.06408275,  0.09523465, -0.04732687, -0.09974216,
        0.14727431,  0.05026918, -0.09878277,  0.12944148,  0.0511039 ])

In [14]:
np.set_printoptions(precision = 2) #指定好小数点的精度

In [15]:
mu, sigma = 0,0.1
np.random.normal(mu,sigma,10)

array([ 0.02, -0.12,  0.11,  0.02, -0.03,  0.15,  0.03,  0.04,  0.01,
       -0.01])

### 洗牌

In [18]:
tang_array = np.arange(10)
tang_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.random.shuffle(tang_array)

In [20]:
tang_array

array([2, 8, 6, 4, 7, 5, 9, 0, 3, 1])

### 随机的种子

In [46]:
np.random.seed(100) #指定一个随机种子，得到的结果相似或者香菇在可变化的范围

In [49]:
mu, sigma = 0,0.1
np.random.normal(mu,sigma,10)

array([ 0.16,  0.15, -0.03, -0.08,  0.02,  0.09,  0.07,  0.14, -0.03,
        0.01])